services:
  - name: fastapi-app
    type: web
    runtime: python
    repo: lakshan19971018/UserManagementAI
    branch: main
    buildCommand: pip install -r requirements.txt
    #alembic upgrade head  # Run database migrations
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000
      - key: DB_USERNAME
        value: sql12763886
      - key: DB_PASSWORD
        value: mDb37338sy
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_DATABASE
        value: sql12763886
      - key: DATABASE_URL
        value: mysql://sql12763886:mDb37338sy@sql12.freesqldatabase.com/sql12763886
      - key: GORQ_API
        value: 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

