services:
  - name: fastapi-app
    type: web
    runtime: python
    repo: lakshan19971018/UserManagementAI
    branch: main
    buildCommand: pip install -r requirements.txt
    #alembic upgrade head  # Run database migrations
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        value: mongodb+srv://lakshan200:ABCDEf45@cluster0.ijlzf.mongodb.net/users?retryWrites=true&w=majority
      - key: GORQ_API
        value: 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

